const orderStatuses = {
  localization: [
    "Vendor Selection",
    "Vendor Assigned",
    "Vendor Accepted",
    "Gate 0",
    "Gate 1",
    "Gate 2",
    "Gate 3",
    "Gate 4",
    "Gate 5",
    "Gate 6",
    "Gate 7",
    "Order completed",
  ],
  contract_manufacturing: [
    "Vendor Selection",
    "Vendor Assigned",
    "Vendor Accepted",
    "PO Release",
    "Drawing Submission",
    "Drawing Approval",
    "Manufacturing clearance",
    "Inspection",
    "Dispatch Clearance",
    "Material Receipt",
    "GRN",
    "Order completed",
  ],
  supply_chain: [
    "Vendor Selection",
    "Vendor Assigned",
    "Vendor Accepted",
    "PO Release",
    "Drawing / Data Sheet Verification",
    "Manufacturing clearance",
    "Inspection",
    "Dispatch Clearance",
    "Material Receipt",
    "GRN",
    "Order completed",
  ],
};

export default orderStatuses;
